### ISSUE TITLE
Site design question

### ISSUE THREAD

**Issue by mattyjones** [BlackArch/blackarch-old-site#3]
Curious as to why you designed the such as such and if you would like a help with it.  I was thinking of possibly using RoR and maybe converting the html to markdown for ease of content generation.

Just thinking out loud here.

**Comment by ghost** [comment]
None of us are web developers. We tried our best at least. ;)

We'd like to keep the site static for security reasons. A bunch of shell scripts seemed to be the easiest way to throw things together.

I setup the site to use markdown once but somebody preferred raw html so I changed it back. I'll talk to him again. Maybe he'll change his mind.

Thanks for the input. Feel free to contribute style changes and/or more ideas.

**Comment by mattyjones** [comment]
I can agree with that and the security and simplicity reasons.  I forked it
and will play with it some, leaving it static and see what I come up with.
I am no I web developer either but I consider myself competent.

**Comment by ldionmarcil** [comment]
Any advancement on this? I'm curious of the result!

**Comment by mattyjones** [comment]
I haven't put much time into coding it as I was waiting for a go ahead.  The owners want to keep things simple.  I can do simple but don't want to put a ton of work into a somewhat cohesive design without a proper consensus.
